#!/usr/bin/env bash
#
# Parse every .xtm file in an Extempore checkout and fail if any produces a
# parse error. This is the broad regression net: the hand-written corpus tests
# pin specific constructs, but this catches coverage gaps against real code.
#
# Usage:
#   script/parse-corpus.sh [path-to-extempore]
#
# With no argument it shallow-clones extemporelang/extempore into a temp dir.
# The aot-cache/ and build/ trees are skipped (generated bytecode, not source).

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
src="${1:-}"

if [[ -z "$src" ]]; then
  src="$(mktemp -d)/extempore"
  echo "Cloning digego/extempore (shallow) into $src ..."
  git clone --depth 1 https://github.com/digego/extempore "$src"
fi

if [[ ! -d "$src" ]]; then
  echo "error: '$src' is not a directory" >&2
  exit 2
fi

list="$(mktemp)"
trap 'rm -f "$list"' EXIT
find "$src" -name '*.xtm' \
  -not -path '*/aot-cache/*' \
  -not -path '*/build/*' \
  -not -path '*/.git/*' \
  -not -path '*/.claude/*' > "$list"

count="$(wc -l < "$list" | tr -d ' ')"
echo "Parsing $count .xtm files from $src ..."

# tree-sitter parse exits non-zero if any file has an ERROR/MISSING node.
if npx tree-sitter parse --quiet --paths "$list"; then
  echo "All $count files parsed cleanly."
else
  echo "FAILED: one or more files above contain parse errors." >&2
  exit 1
fi
